### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/vagrantssh#14]
reponame vagrantssh seems confusing. We can rename it to something like : 
1: contivssh
2: remotessh

**Comment by erikh** [comment]
I changed it to remotessh. cc @mapuri @shaleman @jainvipin

**Comment by erikh** [comment]
@gaurav-dalvi if you don't mind rewriting the readme to reflect the changes in the system, I would really appreciate it.

**Comment by shaleman** [comment]
👍
